Notepad_homework
marzipanka/epam_homework pull request #3
Opened 2019-03-27 20:25 UTC by marzipanka

2019-04-02 13:19 UTC, AnnaS91 requested changes

2019-04-02 13:19 UTC, AnnaS91 commented on Note.java
> +    Note(String headline, String text) {
почему отсутствует модификатор доступа?

2019-04-02 13:19 UTC, AnnaS91 commented on Notepad.java
> +    private Note[] arr;      //массив для хранения записей
лучше давать более говорящие названия, чтобы было понятно, за что именно отвечает переменная (например, notes)

2019-04-02 13:19 UTC, AnnaS91 commented on Notepad.java
> +    private  int lastEmpty;           //lastEmpty отвечает за последнюю свободную ячейку массива
комментарии лучше располагать над строкой, за которую они отвечают

2019-04-02 13:19 UTC, AnnaS91 commented on Notepad.java
> +    Notepad() {
модификатор доступа

2019-04-02 13:19 UTC, AnnaS91 commented on Notepad.java
> +        arr = new Note[10];
10 нужно вынести в константу класса

2019-04-02 13:19 UTC, AnnaS91 commented on Notepad.java
> +        return lastEmpty;
а Вам точно нужно возвращать наружу этот индекс?

2019-04-02 13:19 UTC, AnnaS91 commented on Notepad.java
> +    void create(String headline, String text) {                                        //создать запись
почему не используете модификаторы доступа?

2019-04-02 13:19 UTC, AnnaS91 commented on Notepad.java
> +        if (((lastEmpty+1)%10)==0) {                    //проверяем, заканчивается ли место в массиве
а почему именно такая проверка? почему не проверить, что индекс сравнялся с длинной?

2019-04-02 13:19 UTC, AnnaS91 commented on Notepad.java
> +            arr = new Note[arr.length + 10];
различные числа нужно выносить в константы

2019-04-02 13:19 UTC, AnnaS91 commented on Notepad.java
> +     void delete(int number) {                    //удалить запись
модификатор доступа, комментарий на предыдущей строке

2019-04-02 13:19 UTC, AnnaS91 commented on Notepad.java
> +        for (int i = number - 1; i < arr.length - 1; i++) {       //переписываем массив
а зачем Вы копируете окончание массива, где одни null?

2019-04-02 13:19 UTC, AnnaS91 commented on Notepad.java
> +        arr[number-1] = new Note(headline, text);
логичнее было бы иметь методы для редактирования headline и text по отдельности

2019-04-02 13:19 UTC, AnnaS91 commented on Notepad.java
> +     void seeAll() {           //посмотреть все записи
почему удалили public?

2019-04-02 13:19 UTC, AnnaS91 commented on Notepad.java
> +    public Note[] getArr() {
это очень опасный метод, советую Вам его удалить. Возвращая пользователю Ваш внутрениий массив, Вы разрешаете ему этот массив модифицировать, но при этом Ваши внутренние параметры не поменяются и большинство Ваших методов станут неработающими

2019-04-02 17:51 UTC, marzipanka commented on Notepad.java
> +    public Note[] getArr() {
Я использую этот метод в тестах, чтобы проверить значения в массиве после манипуляций с ним. Можно ли сделать этот метод protected или default?) Или как тогда вытаскивать массив для тестов?

2019-04-03 11:52 UTC, AnnaS91 requested changes

2019-04-03 11:52 UTC, AnnaS91 commented on Notepad.java
> +            for (int i = 0; i < notes.length; i++) {
а зачем Вам цикл, в котором ничего не происходит?

2019-04-03 11:52 UTC, AnnaS91 commented on Notepad.java
>              for (int i = 0; i < extraArr.length; i++) {
extraArr пустой

2019-04-03 11:52 UTC, AnnaS91 commented on Notepad.java
> +         notes[number-1] = new Note(headline, notes[number-1].getText());
а почему не создать методы для редактирования заголовка уже существующей записи (setHeadline)

2019-04-03 11:52 UTC, AnnaS91 commented on Notepad.java
> +        notes[number-1] = new Note(notes[number-1].getHeadline(), text);
аналогичный вопрос

2019-04-04 08:08 UTC, AnnaS91 requested changes
в тестах можно было бы попробовать использовать названия в стиле BDD (deleteShouldDecreaseSize и т.п.)

2019-04-04 08:08 UTC, AnnaS91 commented on Notepad.java
> +        lastEmpty--;
когда мы несколько раз расширяем массив, а потом удаляем несколько записей, было бы правильным попробовать уменьшить размер массива, например в половину

2019-04-04 16:21 UTC, AnnaS91 requested changes

2019-04-04 16:21 UTC, AnnaS91 commented on Notepad.java
> +        if(notes.length-lastEmpty > notes.length/2) {
здесь нужно добавить проверку, что размер превышает первоначальный, иначе у вас сразу же уменьшиться размер. Уменьшать лучше не в половину, а с каким-нибудь коэф. Например, когда свободно 3/4, то тогда в половину

2019-04-04 21:53 UTC, AnnaS91 approved these changes
Зачтено :)

2019-04-05 09:54 UTC, merged